format = """
[░▒▓](#abb2bf)\
[  ](bg:#abb2bf fg:#090c0c)\
[](bg:#61afef fg:#abb2bf)\
$directory\
[](fg:#61afef bg:#5b6268)\
$git_branch\
$git_status\
[](fg:#5b6268 bg:#3f444a)\
$nodejs\
$python\
$golang\
$lua\
[](fg:#3f444a bg:#23272e)\
$cmd_duration\
[ ](fg:#23272e)\
\n$character"""

[directory]
style = "fg:#15161e bg:#61afef"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#5b6268"
format = '[[ $symbol $branch ](fg:#46d9ff bg:#5b6268)]($style)'

[git_status]
style = "bg:#5b6268"
ahead = '[ ($count)](fg:green bg:#5b6268)'
untracked = '[ ($count)](fg:red bg:#5b6268)'
modified = '[  ($count)](fg:yellow bg:#5b6268)'
deleted = '[  ($count)](fg:red bg:#5b6268)'
format = '[[$all_status$ahead_behind](bg:#5b6268)]($style)'

[nodejs]
symbol = " "
style = "bg:#3f444a"
format = '[[ $symbol ($version) ](fg:#61afef bg:#3f444a)]($style)'

[python]
symbol = " "
style = "bg:#3f444a"
format = '[[ $symbol ($version) ](fg:#61afef bg:#3f444a)]($style)'

[golang]
symbol = "  "
style = "bg:#3f444a"
format = '[[ $symbol ($version) ](fg:#61afef bg:#3f444a)]($style)'

[lua]
symbol = " "
style = "bg:#3f444a"
format = '[[ $symbol ($version) ](fg:#61afef bg:#3f444a)]($style)'

[cmd_duration]
disabled = false
style = "bg:#23272e"
format = '[[  $duration ](fg:#e5c07b bg:#23272e)]($style)'

[character]
disabled = false
success_symbol = '[⮞ ](bold fg:#98c379)'
error_symbol = '[⮞ ](bold fg:#e06c75)'
