[character]
success_symbol = '[next ](green)'
error_symbol = '[next ](red)'

[git_branch]
symbol = ' '

[git_status]
ahead = '  ($count)'
behind = '  ($count)'
diverged = ' '
untracked = '  '
stashed = '  '
modified = '  ($count)'
staged = '  '
renamed = '  '
deleted = '  '
