" ====== vimrc by Rob Boudreau ======
" ====== Last change:	13 Sep 2018 ======

    " Set font and some optionsfor GVim
if has('gui_running')
  set guifont=Iosevka\ 12
  set guioptions=m
endif

    " Call and/or install plugins with vim-plug
call plug#begin('~/.vim/plugged')

" Plug 'https://github.com/ctrlpvim/ctrlp.vim.git'
Plug 'Shougo/denite.nvim'
Plug 'scrooloose/nerdtree'
Plug 'itchyny/lightline.vim'
Plug 'taohexxx/lightline-buffer'
" Plug 'mkarmona/materialbox.git'
" Plug 'arcticicestudio/nord-vim'
Plug 'joshdick/onedark.vim'
" Plug 'lifepillar/vim-solarized8'
Plug 'lilydjwg/colorizer'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fugitive'
Plug 'godlygeek/tabular'
Plug 'eugen0329/vim-esearch'
Plug 'majutsushi/tagbar'
Plug 'lvht/tagbar-markdown'
Plug 'ryanoasis/vim-devicons'
Plug 'plasticboy/vim-markdown'

call plug#end()

    " Enable filetype detection.
filetype plugin indent on
syntax enable

    " Set global options
set conceallevel=3
set concealcursor=nc
set termguicolors
set encoding=utf-8
set expandtab
set tabstop=4
set shiftwidth=4
set backspace=indent,eol,start
set history=50
set ruler
set showcmd
set incsearch
set laststatus=2
set showtabline=2
set linebreak
set wildmenu
set wildmode=list:longest,full
set ttimeoutlen=50
set dir=~/Temp
set splitbelow
set splitright
set noswapfile
" syntax on
set hlsearch
set number
set relativenumber
set autoindent
" set backupdir=~/Temp
set nobackup
set nowritebackup
set noshowmode
" set foldenable

    " Settings for Vim-Markdown
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_follow_anchor = 1
" let g:vim_markdown_autowrite = 1
nno <leader>t :TableFormat<cr>

    " --{{ Settings for vim-esearch
let g:esearch = {
  \ 'adapter':    'rg',
  \ 'backend':    'system',
  \ 'out':        'qflist',
  \ 'batch_size': 1000,
  \ 'use':        ['word_under_cursor'],
  \ 'default_mappings': 1,
  \}
let g:esearch#out#win#open = 'split'
    " --}} end of settings for vim-esearch

    " This is suppose to allow file links to be opened with 'gx'
let g:netrw_browsex_viewer = "xdg-open"

    " This is supposed to allow italics in terminal
" set t_ZH=[3m
" set t_ZR=[23m

    " --{{ Settings for Lightline
let g:lightline = {
    \ 'colorscheme': 'one',
    \ 'tabline': {
    \   'left': [ [ 'bufferinfo' ],
    \             [ 'separator' ],
    \             [ 'bufferbefore', 'buffercurrent', 'bufferafter' ], ],
    \   'right': [ [ 'close' ], ],
    \ },
    \ 'component_expand': {
    \   'buffercurrent': 'lightline#buffer#buffercurrent',
    \   'bufferbefore': 'lightline#buffer#bufferbefore',
    \   'bufferafter': 'lightline#buffer#bufferafter',
    \ },
    \ 'component_type': {
    \   'buffercurrent': 'tabsel',
    \   'bufferbefore': 'raw',
    \   'bufferafter': 'raw',
    \ },
    \ 'component_function': {
    \   'bufferinfo': 'lightline#buffer#bufferinfo',
    \ },
    \ 'component': {
    \   'separator': '',
    \ },
    \ }
    " --}} End of Lightline settings

    "Denite settings copied from 
" reset 50% winheight on window resize
augroup deniteresize
  autocmd!
  autocmd VimResized,VimEnter * call denite#custom#option('default',
        \'winheight', winheight(0) / 2)
augroup end

call denite#custom#option('default', {
      \ 'prompt': '❯'
      \ })

call denite#custom#var('file_rec', 'command',
      \ ['rg', '--files', '--glob', '!.git'])
call denite#custom#var('grep', 'command', ['rg'])
call denite#custom#var('grep', 'default_opts',
      \ ['--hidden', '--vimgrep', '--smart-case'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'pattern_opt', ['--regexp'])
call denite#custom#var('grep', 'separator', ['--'])
call denite#custom#var('grep', 'final_opts', [])
call denite#custom#map('insert', '<Esc>', '<denite:enter_mode:normal>',
      \'noremap')
call denite#custom#map('normal', '<Esc>', '<NOP>',
      \'noremap')
call denite#custom#map('insert', '<C-v>', '<denite:do_action:vsplit>',
      \'noremap')
call denite#custom#map('normal', '<C-v>', '<denite:do_action:vsplit>',
      \'noremap')
call denite#custom#map('normal', 'dw', '<denite:delete_word_after_caret>',
      \'noremap')

nnoremap <C-p> :<C-u>Denite file_rec<CR>
nnoremap <leader>s :<C-u>Denite buffer<CR>
nnoremap <leader><Space>s :<C-u>DeniteBufferDir buffer<CR>
nnoremap <leader>8 :<C-u>DeniteCursorWord grep:. -mode=normal<CR>
nnoremap <leader>/ :<C-u>Denite grep:. -mode=normal<CR>
nnoremap <leader><Space>/ :<C-u>DeniteBufferDir grep:. -mode=normal<CR>
nnoremap <leader>d :<C-u>DeniteBufferDir file_rec<CR>
nnoremap <leader>r :<C-u>Denite -resume -cursor-pos=+1<CR>
nnoremap <leader>lr :<C-u>Denite references -mode=normal<CR>

hi link deniteMatchedChar Special
    " End Denite settings


    " Set up colorschemes
let g:onedark_terminal_italics = 1
" let g:onedark_termcolors = 256
" let g:one_allow_italics = 1

set background=dark
colorscheme onedark
" colorscheme one
" colorscheme solarized8
" colorscheme nord
" colorscheme hybrid_material
" colorscheme base16-ocean
" colorscheme materialbox

    " --{{{ Start of key mappings

    " This is to open markdown in okular
nno <silent><F9> :!okular %:p<cr>

    " These are for auto-brackets
ino " ""<ESC>i
ino { {}<ESC>i
ino [ []<ESC>i
ino ( ()<ESC>i
nno ; :

    " These keep searches centered in the page
nno n nzzzv
nno N Nzzzv

    " These increase/decrease window split sizes
nno <A-left> <c-w>>
nno <A-right> <c-w><
nno <A-up> <c-w>+
nno <A-down> <c-w>-

    " This turns off search highlighting
nno <silent><leader>\ :noh<cr>

    "Make moving back and forth in buffers easier
nno <silent><leader>[ :bp<cr>
nno <silent><leader>] :bn<cr>

    " This closes the currently viewed buffer and loads the last in the window
nno <silent><leader>c :bp\|bd #<CR>

    " This makes unrecognized code files use shell syntax highlighting
nno <F5> :set syntax=sh<cr>

    "Makes moving throught windows more sane
nno <C-j> <C-w>j
nno <C-k> <C-w>k
nno <C-h> <C-w>h
nno <C-l> <C-w>l

     " Make moving through lines normal, instead of jumping past wraps
nno <silent> <Up> gk
nno <silent> <Down> gj
nno <expr> k (v:count? 'k' : 'gk')
nno <expr> j (v:count? 'j' : 'gj')

    " Do a search through current project files for selected word
nno <leader>s :execute "vimgrep /" . expand("<cword>") . "/j **" <Bar> cw<CR>

    " Move lines up or down using CTRL+arrow key
nno <C-down> ddp
nno <C-up> ddkP

    " Copy and paste
vmap <C-c> "+yi
vmap <C-x> "+c
vmap <C-v> c<ESC>"+p
imap <C-v> <ESC>"+pa

    " Cleans up trailing whitespace from current edit
nno <leader>w :%s/\s\+$//<cr>:let @/=''<cr>

    " Control keys for CtrlP to open it in different modes
" let g:ctrlp_map = '<C-p>'
" let g:ctrlp_cmd = 'CtrlP'
" nno <leader>b :CtrlPBuffer<cr>
" nno <leader>p :CtrlPMRU<cr>

    " zoom a vim pane, <C-w>- to re-balance
nno <leader>+ :wincmd =<cr>:wincmd \|<cr>
nno <leader>- :wincmd =<cr>

    " Open the markdown outline
    " and put it on the left side
nno <F8> :TagbarToggle<cr>
ino <F8> :TagbarToggle<cr>
let g:tagbar_left=1

    " Snippets
nno <leader>= o==================================================<cr><ESC>

    " Save current session using existing or new name
nno <leader>q :mks! ~/.vim/sessions/
    " Load existing session
nno <leader>l :source ~/.vim/sessions/

    " Settings for NerdTree so it's more sane
nno <silent><leader>n :NERDTreeToggle<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
let g:NERDTreeHijackNetrw=1
let NERDTreeShowBookmarks=1
let NERDTreeShowHidden=1
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'
nno <silent><leader>e :edit .<cr>

    " Save a admin file from regular user
nno :w!! :w !sudo tee %

    " Don't use Ex mode, use Q for formatting
map Q gq

    " automatically rebalance windows on vim resize
autocmd VimResized * :wincmd =

    " Set the file selection window to tree view
    " CTRL-U in insert mode deletes a lot.  Use CTRL-G u to first break undo,
    " so that you can undo CTRL-U after inserting a line break.
ino <C-U> <C-G>u<C-U>

" }}}-- End of mappings

    " In many terminal emulators the mouse works just fine, thus enable it.
if has('mouse')
  set mouse=a
endif

    " Only do this part when compiled with support for autocommands.
" if has("autocmd")

"     " Put these in an autocmd group, so that we can delete them easily.
" augroup vimrcEx
" au!

"     " When editing a file, always jump to the last known cursor position.
"     " Don't do it when the position is invalid or when inside an event handler
"     " (happens when dropping a file on gvim).
"     " Also don't do it when the mark is in the first line, that is the default
"     " position when opening a file.
"   autocmd BufReadPost *
"     \ if line("'\"") > 1 && line("'\"") <= line("$") |
"     \   exe normal! g`\"" |
"     \ endif

"   augroup END

" else

" endif  has("autocmd")

    " Convenient command to see the difference between the current buffer and the
    " file it was loaded from, thus the changes you made.
    " Only define it when not defined already.
if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r ++edit # | 0d_ | diffthis
  \ | wincmd p | diffthis
endif

    " Set the directory depth for CtrlP to open
let g:ctrlp_by_filename = 1
let g:ctrlp_mac_depth = 3
let g:ctrlp_max_files = 0
let g:ctrlp_show_hidden = 1
let g:ctrlp_switch_buffer = 'Et'
let g:ctrlp_working_path_mode = 'w'
highlight Comment cterm=italic
