#! /bin/sh

sxhkd &
polybar mybar &
gnome-keyring-daemon -s &
/usr/lib64/polkit-gnome/polkit-gnome-authentication-agent-1 &
/home/rob/.fehbg &
compton &
tracker daemon -s &
dropbox start -i &
dunst &
xclip &
clipit &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding         30

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config presel_feedback_color "#65737E"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mpv state=floating
bspc rule -a rofi focus=on
bspc rule -a Screenkey manage=off
