#! /bin/sh

xrandr --output DP-1 --primary --output HDMI-1 --right-of DP-1 &
setxkbmap -option caps:ctrl_modifier &
xsetroot -cursor_name left_ptr &
/home/rob/.config/dotfiles/polybar/launch.sh &
/usr/lib/polkit-kde-authentication-agent-1 &
start-pulseaudio-x11 &
ssh-agent &
/home/rob/.fehbg &
picom --experimental-backends &
dunst &
xclip &
clipit &
# gnome-keyring-daemon --start --foreground --components=secrets &
# /usr/lib/pam_kwallet_init &
# ibus-daemon -drxR &
recollindex -m &
sxhkd &

bspc monitor DP-1 -d 1 2 3 4 5
bspc monitor HDMI-1 -d 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          10
bspc config top_padding         26

bspc config split_ratio          0.50
bspc config initial_polarity    second_child
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config presel_feedback_color "#65737E"

bspc rule -a Gimp state=floating follow=on
bspc rule -a org-knopflerfish-framework-BundleThread state=floating center=true
bspc rule -a Sxiv state=floating
bspc rule -a mpv state=floating
bspc rule -a vlc state=floating
bspc rule -a okular state=floating
bspc rule -a rofi focus=on
bspc rule -a Cherrytree state=floating
