#! /bin/sh

sxhkd &
polybar bspwmbar &
gnome-keyring-daemon -s &
/usr/lib64/polkit-gnome/polkit-gnome-authentication-agent-1 &
ssh-agent &
/home/rob/.fehbg &
compton &
dropbox start -i &
# dbus-launch dunst &
xclip &
clipit &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          10
bspc config top_padding         26

bspc config split_ratio          0.50
bspc config initial_polarity    second_child
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config presel_feedback_color "#65737E"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Sxiv state=floating
bspc rule -a mpv state=floating
bspc rule -a okular state=floating
bspc rule -a rofi focus=on
bspc rule -a Cherrytree state=floating
bspc rule -a Zathura state=floating
